// Generated by CoffeeScript 1.11.1
var AnimatedValue, Axis, Event, Gesture, LazyVar, Responder, ResponderSyntheticEvent, Type, emptyFunction, type;

AnimatedValue = require("Animated").AnimatedValue;

Responder = require("gesture").Responder;

ResponderSyntheticEvent = require("ResponderSyntheticEvent");

emptyFunction = require("emptyFunction");

LazyVar = require("LazyVar");

Event = require("Event");

Type = require("Type");

Gesture = require("./Gesture");

Axis = require("./Axis");

type = Type("DragResponder");

type.inherits(Responder);

type.defineOptions({
  axis: Axis.isRequired,
  offset: Number.withDefault(0),
  captureDistance: Number.withDefault(10),
  canDrag: Function.withDefault(emptyFunction.thatReturnsTrue),
  shouldRespondOnStart: Function.withDefault(emptyFunction.thatReturnsFalse),
  shouldCaptureOnMove: Function.withDefault(emptyFunction.thatReturnsTrue)
});

type.defineStatics({
  Gesture: Gesture,
  Axis: Axis
});

type.defineFrozenValues(function(options) {
  return {
    axis: options.axis,
    offset: AnimatedValue(options.offset),
    isHorizontal: options.axis === "x",
    _captureDistance: options.captureDistance,
    _lockedAxis: LazyVar((function(_this) {
      return function() {
        var dx, dy;
        dx = Math.abs(_this.gesture.dx);
        dy = Math.abs(_this.gesture.dy);
        if (_this._isAxisDominant(dx, dy)) {
          return "x";
        }
        if (_this._isAxisDominant(dy, dx)) {
          return "y";
        }
        return null;
      };
    })(this))
  };
});

type.defineValues(function(options) {
  return {
    didDrag: Event({
      argTypes: {
        gesture: Gesture,
        event: ResponderSyntheticEvent
      }
    }),
    _canDrag: options.canDrag
  };
});

type.defineMethods({
  _computeOffset: function(gesture) {
    return gesture.startOffset + gesture.distance;
  },
  _isAxisDominant: function(a, b) {
    return (a - 2) > b && (a >= this._captureDistance);
  },
  _canDragOnStart: function() {
    if (this._canDrag(this.gesture)) {
      return true;
    }
    this.terminate();
    return false;
  },
  _canDragOnMove: function() {
    var lockedAxis;
    if (!this._canDrag(this.gesture)) {
      this.terminate();
      return false;
    }
    lockedAxis = this._lockedAxis.get();
    if (lockedAxis === null) {
      this._lockedAxis.reset();
      return false;
    }
    if (lockedAxis !== this.axis) {
      this.terminate();
      return false;
    }
    return true;
  }
});

type.overrideMethods({
  __createGesture: function(options) {
    options.axis = this.axis;
    options.startOffset = this.offset.get();
    return Gesture(options);
  },
  __shouldRespondOnStart: function() {
    if (!this._canDragOnStart()) {
      return false;
    }
    return this.__super(arguments);
  },
  __shouldRespondOnMove: function() {
    if (!this._canDragOnMove()) {
      return false;
    }
    return this.__super(arguments);
  },
  __shouldCaptureOnStart: function() {
    if (!this._canDragOnStart()) {
      return false;
    }
    return this.__super(arguments);
  },
  __shouldCaptureOnMove: function() {
    if (!this._canDragOnMove()) {
      return false;
    }
    return this.__super(arguments);
  },
  __onTouchMove: function(event) {
    this.gesture.__onTouchMove(event);
    if (this._isGranted) {
      this.offset.set(this._computeOffset(this.gesture));
      this.didDrag.emit(this.gesture, event);
    }
    this.didTouchMove.emit(this.gesture, event);
  },
  __onTouchEnd: function(event) {
    var touches;
    touches = event.nativeEvent.touches;
    if (touches.length === 0) {
      this._lockedAxis.reset();
    }
    return this.__super(arguments);
  },
  __onGrant: function() {
    this.offset.stopAnimation();
    this.__super(arguments);
    return this.gesture._startOffset = this.offset.get() - this.gesture.distance;
  }
});

module.exports = type.build();
