// Generated by CoffeeScript 1.12.4
var Gesture, Type, Velocity, type;

Velocity = require("Velocity");

Gesture = require("gesture");

Type = require("Type");

type = Type("DragResponder_Gesture");

type.inherits(Gesture);

type.defineArgs(function() {
  return {
    required: true,
    types: {
      axis: String
    }
  };
});

type.defineGetters({
  startDistance: function() {
    if (this._horizontal) {
      return this.dx0;
    } else {
      return this.dy0;
    }
  },
  distance: function() {
    if (this._horizontal) {
      return this.dx - this.dx0;
    } else {
      return this.dy - this.dy0;
    }
  },
  velocity: function() {
    return this._velocity.get();
  },
  direction: function() {
    return this._velocity.direction;
  }
});

type.defineValues(function(options) {
  return {
    _horizontal: options.axis === "x",
    _velocity: Velocity({
      maxAge: 300
    })
  };
});

type.overrideMethods({
  __onTouchStart: function() {
    this.__super(arguments);
    this._velocity.reset();
  },
  __onTouchMove: function() {
    this.__super(arguments);
    this._velocity.update(Date.now(), this.distance);
  }
});

module.exports = type.build();
